
# Tasks to run on workspace start
tasks:
  - name: AWS CLI
    env: 
      export AWS_CLI_AUTO_PROMPT=on-partial
    before: |
      sudo apt-get update -y
      sudo apt-get install -y unzip
      cd ~
      curl -sS "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
      unzip -o awscliv2.zip
      sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      cd $OLDPWD
